### ISSUE TITLE
A Generate of Data Scheme

### ISSUE THREAD

**Issue by codybak4** [taviroquai/db2graphql#46]
The base64 encoding is designed to represent arbitrary sequences of
octets in a form that need not be humanly readable. A 65-character
subset ([A-Za-z0-9+/=]) of US-ASCII is used, enabling 6 bits to be
represented per printable character.

**Comment by Cadienvan** [comment]
Hi @codybak4 , thank you for opening the issue.

I'm not getting your point. Is there anything you want us to do about it?
